/**
 * Stock Universe for Screener
 *
 * ~500 most actively traded US equities and ETFs,
 * sorted roughly by market cap / options liquidity.
 * GEX/DEX signals are most reliable where open interest and volume are highest.
 */

export interface UniverseStock {
  symbol: string;
  name: string;
  sector: string;
}

export const STOCK_UNIVERSE: UniverseStock[] = [
  // ── Major Index & Broad Market ETFs ──
  { symbol: 'SPY', name: 'S&P 500 ETF', sector: 'ETF' },
  { symbol: 'QQQ', name: 'Nasdaq 100 ETF', sector: 'ETF' },
  { symbol: 'IWM', name: 'Russell 2000 ETF', sector: 'ETF' },
  { symbol: 'DIA', name: 'Dow Jones ETF', sector: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500', sector: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Market', sector: 'ETF' },
  { symbol: 'MDY', name: 'S&P MidCap 400 ETF', sector: 'ETF' },

  // ── Sector ETFs ──
  { symbol: 'XLF', name: 'Financial Select Sector', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select Sector', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select Sector', sector: 'ETF' },
  { symbol: 'XLV', name: 'Healthcare Select Sector', sector: 'ETF' },
  { symbol: 'XLI', name: 'Industrial Select Sector', sector: 'ETF' },
  { symbol: 'XLC', name: 'Communication Services', sector: 'ETF' },
  { symbol: 'XLU', name: 'Utilities Select Sector', sector: 'ETF' },
  { symbol: 'XLP', name: 'Consumer Staples Select', sector: 'ETF' },
  { symbol: 'XLY', name: 'Consumer Discretionary', sector: 'ETF' },
  { symbol: 'XLB', name: 'Materials Select Sector', sector: 'ETF' },
  { symbol: 'XLRE', name: 'Real Estate Select', sector: 'ETF' },

  // ── Thematic & Specialty ETFs ──
  { symbol: 'GLD', name: 'Gold ETF', sector: 'ETF' },
  { symbol: 'SLV', name: 'Silver ETF', sector: 'ETF' },
  { symbol: 'TLT', name: '20+ Year Treasury ETF', sector: 'ETF' },
  { symbol: 'HYG', name: 'High Yield Bond ETF', sector: 'ETF' },
  { symbol: 'EEM', name: 'Emerging Markets ETF', sector: 'ETF' },
  { symbol: 'SMH', name: 'Semiconductor ETF', sector: 'ETF' },
  { symbol: 'SOXX', name: 'iShares Semiconductor', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', sector: 'ETF' },
  { symbol: 'KWEB', name: 'China Internet ETF', sector: 'ETF' },
  { symbol: 'IBB', name: 'Biotech ETF', sector: 'ETF' },
  { symbol: 'XBI', name: 'SPDR Biotech ETF', sector: 'ETF' },
  { symbol: 'XOP', name: 'Oil & Gas Exploration ETF', sector: 'ETF' },
  { symbol: 'XRT', name: 'Retail ETF', sector: 'ETF' },
  { symbol: 'XHB', name: 'Homebuilders ETF', sector: 'ETF' },
  { symbol: 'JETS', name: 'Airlines ETF', sector: 'ETF' },
  { symbol: 'KRE', name: 'Regional Banking ETF', sector: 'ETF' },
  { symbol: 'FXI', name: 'China Large-Cap ETF', sector: 'ETF' },
  { symbol: 'EWZ', name: 'Brazil ETF', sector: 'ETF' },
  { symbol: 'USO', name: 'United States Oil Fund', sector: 'ETF' },
  { symbol: 'GDX', name: 'Gold Miners ETF', sector: 'ETF' },
  { symbol: 'GDXJ', name: 'Junior Gold Miners ETF', sector: 'ETF' },
  { symbol: 'LQD', name: 'Investment Grade Bond ETF', sector: 'ETF' },
  { symbol: 'IBIT', name: 'iShares Bitcoin Trust', sector: 'ETF' },
  { symbol: 'BITO', name: 'ProShares Bitcoin ETF', sector: 'ETF' },

  // ── Mega Cap Tech ──
  { symbol: 'AAPL', name: 'Apple', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Technology' },
  { symbol: 'NVDA', name: 'NVIDIA', sector: 'Technology' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Technology' },
  { symbol: 'TSLA', name: 'Tesla', sector: 'Technology' },
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Technology' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Technology' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology' },
  { symbol: 'AMD', name: 'AMD', sector: 'Technology' },
  { symbol: 'INTC', name: 'Intel', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe', sector: 'Technology' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'MU', name: 'Micron', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Technology' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Technology' },
  { symbol: 'SNOW', name: 'Snowflake', sector: 'Technology' },
  { symbol: 'PLTR', name: 'Palantir', sector: 'Technology' },
  { symbol: 'ARM', name: 'ARM Holdings', sector: 'Technology' },
  { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },
  { symbol: 'SMCI', name: 'Super Micro Computer', sector: 'Technology' },
  { symbol: 'DELL', name: 'Dell Technologies', sector: 'Technology' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Technology' },
  { symbol: 'HPQ', name: 'HP Inc', sector: 'Technology' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Technology' },
  { symbol: 'DDOG', name: 'Datadog', sector: 'Technology' },
  { symbol: 'ZS', name: 'Zscaler', sector: 'Technology' },
  { symbol: 'FTNT', name: 'Fortinet', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys', sector: 'Technology' },
  { symbol: 'CDNS', name: 'Cadence Design', sector: 'Technology' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Technology' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { symbol: 'ON', name: 'ON Semiconductor', sector: 'Technology' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'MCHP', name: 'Microchip Technology', sector: 'Technology' },
  { symbol: 'SWKS', name: 'Skyworks Solutions', sector: 'Technology' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Technology' },
  { symbol: 'WDAY', name: 'Workday', sector: 'Technology' },
  { symbol: 'TEAM', name: 'Atlassian', sector: 'Technology' },
  { symbol: 'HUBS', name: 'HubSpot', sector: 'Technology' },
  { symbol: 'MDB', name: 'MongoDB', sector: 'Technology' },
  { symbol: 'DOCU', name: 'DocuSign', sector: 'Technology' },
  { symbol: 'TWLO', name: 'Twilio', sector: 'Technology' },
  { symbol: 'ZM', name: 'Zoom Video', sector: 'Technology' },
  { symbol: 'OKTA', name: 'Okta', sector: 'Technology' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Technology' },
  { symbol: 'SNAP', name: 'Snap Inc', sector: 'Technology' },
  { symbol: 'PINS', name: 'Pinterest', sector: 'Technology' },
  { symbol: 'RBLX', name: 'Roblox', sector: 'Technology' },
  { symbol: 'U', name: 'Unity Software', sector: 'Technology' },
  { symbol: 'PATH', name: 'UiPath', sector: 'Technology' },
  { symbol: 'BILL', name: 'BILL Holdings', sector: 'Technology' },
  { symbol: 'TTD', name: 'The Trade Desk', sector: 'Technology' },
  { symbol: 'ROKU', name: 'Roku', sector: 'Technology' },
  { symbol: 'LYFT', name: 'Lyft', sector: 'Technology' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Technology' },
  { symbol: 'SPOT', name: 'Spotify', sector: 'Technology' },
  { symbol: 'SQ', name: 'Block (Square)', sector: 'Technology' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Technology' },
  { symbol: 'AFRM', name: 'Affirm Holdings', sector: 'Technology' },
  { symbol: 'HOOD', name: 'Robinhood Markets', sector: 'Technology' },
  { symbol: 'IONQ', name: 'IonQ', sector: 'Technology' },
  { symbol: 'AI', name: 'C3.ai', sector: 'Technology' },
  { symbol: 'UPST', name: 'Upstart Holdings', sector: 'Technology' },
  { symbol: 'APP', name: 'AppLovin', sector: 'Technology' },
  { symbol: 'ESTC', name: 'Elastic NV', sector: 'Technology' },
  { symbol: 'CFLT', name: 'Confluent', sector: 'Technology' },
  { symbol: 'GTLB', name: 'GitLab', sector: 'Technology' },
  { symbol: 'IOT', name: 'Samsara', sector: 'Technology' },
  { symbol: 'MNDY', name: 'Monday.com', sector: 'Technology' },
  { symbol: 'DKNG', name: 'DraftKings', sector: 'Technology' },
  { symbol: 'ASAN', name: 'Asana', sector: 'Technology' },
  { symbol: 'RDDT', name: 'Reddit', sector: 'Technology' },
  { symbol: 'GRAB', name: 'Grab Holdings', sector: 'Technology' },
  { symbol: 'SE', name: 'Sea Limited', sector: 'Technology' },
  { symbol: 'BABA', name: 'Alibaba', sector: 'Technology' },
  { symbol: 'JD', name: 'JD.com', sector: 'Technology' },
  { symbol: 'PDD', name: 'PDD Holdings', sector: 'Technology' },
  { symbol: 'BIDU', name: 'Baidu', sector: 'Technology' },

  // ── Finance ──
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Finance' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Finance' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Finance' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance' },
  { symbol: 'V', name: 'Visa', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Finance' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway', sector: 'Finance' },
  { symbol: 'C', name: 'Citigroup', sector: 'Finance' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance' },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Finance' },
  { symbol: 'SOFI', name: 'SoFi Technologies', sector: 'Finance' },
  { symbol: 'USB', name: 'US Bancorp', sector: 'Finance' },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Finance' },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Finance' },
  { symbol: 'BK', name: 'Bank of New York Mellon', sector: 'Finance' },
  { symbol: 'AIG', name: 'American Intl Group', sector: 'Finance' },
  { symbol: 'MET', name: 'MetLife', sector: 'Finance' },
  { symbol: 'PRU', name: 'Prudential Financial', sector: 'Finance' },
  { symbol: 'ALL', name: 'Allstate', sector: 'Finance' },
  { symbol: 'TRV', name: 'Travelers Companies', sector: 'Finance' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Finance' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Finance' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Finance' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Finance' },
  { symbol: 'CME', name: 'CME Group', sector: 'Finance' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Finance' },
  { symbol: 'MCO', name: 'Moody\'s', sector: 'Finance' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Finance' },
  { symbol: 'KKR', name: 'KKR & Co', sector: 'Finance' },
  { symbol: 'APO', name: 'Apollo Global', sector: 'Finance' },
  { symbol: 'ARES', name: 'Ares Management', sector: 'Finance' },
  { symbol: 'FIS', name: 'Fidelity National Info', sector: 'Finance' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Finance' },
  { symbol: 'RF', name: 'Regions Financial', sector: 'Finance' },
  { symbol: 'CFG', name: 'Citizens Financial', sector: 'Finance' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Finance' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Finance' },
  { symbol: 'DFS', name: 'Discover Financial', sector: 'Finance' },
  { symbol: 'COF', name: 'Capital One Financial', sector: 'Finance' },
  { symbol: 'ALLY', name: 'Ally Financial', sector: 'Finance' },
  { symbol: 'WAL', name: 'Western Alliance', sector: 'Finance' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc', sector: 'Finance' },
  { symbol: 'MARA', name: 'Marathon Digital', sector: 'Finance' },
  { symbol: 'RIOT', name: 'Riot Platforms', sector: 'Finance' },
  { symbol: 'NU', name: 'Nu Holdings', sector: 'Finance' },

  // ── Healthcare ──
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Healthcare' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { symbol: 'ABT', name: 'Abbott Labs', sector: 'Healthcare' },
  { symbol: 'DHR', name: 'Danaher', sector: 'Healthcare' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
  { symbol: 'SYK', name: 'Stryker', sector: 'Healthcare' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Healthcare' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
  { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Healthcare' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'REGN', name: 'Regeneron', sector: 'Healthcare' },
  { symbol: 'BIIB', name: 'Biogen', sector: 'Healthcare' },
  { symbol: 'ILMN', name: 'Illumina', sector: 'Healthcare' },
  { symbol: 'DXCM', name: 'DexCom', sector: 'Healthcare' },
  { symbol: 'IDXX', name: 'IDEXX Labs', sector: 'Healthcare' },
  { symbol: 'IQV', name: 'IQVIA Holdings', sector: 'Healthcare' },
  { symbol: 'A', name: 'Agilent Technologies', sector: 'Healthcare' },
  { symbol: 'CI', name: 'Cigna Group', sector: 'Healthcare' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { symbol: 'HUM', name: 'Humana', sector: 'Healthcare' },
  { symbol: 'CNC', name: 'Centene', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare' },
  { symbol: 'MCK', name: 'McKesson', sector: 'Healthcare' },
  { symbol: 'CAH', name: 'Cardinal Health', sector: 'Healthcare' },
  { symbol: 'NVO', name: 'Novo Nordisk', sector: 'Healthcare' },
  { symbol: 'AZN', name: 'AstraZeneca', sector: 'Healthcare' },
  { symbol: 'SNY', name: 'Sanofi', sector: 'Healthcare' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Healthcare' },
  { symbol: 'ALGN', name: 'Align Technology', sector: 'Healthcare' },
  { symbol: 'PODD', name: 'Insulet', sector: 'Healthcare' },
  { symbol: 'HIMS', name: 'Hims & Hers Health', sector: 'Healthcare' },
  { symbol: 'CORT', name: 'Corcept Therapeutics', sector: 'Healthcare' },

  // ── Consumer Discretionary ──
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer' },
  { symbol: 'COST', name: 'Costco', sector: 'Consumer' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer' },
  { symbol: 'MCD', name: 'McDonald\'s', sector: 'Consumer' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer' },
  { symbol: 'LOW', name: 'Lowe\'s', sector: 'Consumer' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Consumer' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer' },
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Consumer' },
  { symbol: 'LULU', name: 'Lululemon', sector: 'Consumer' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer' },
  { symbol: 'MAR', name: 'Marriott', sector: 'Consumer' },
  { symbol: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer' },
  { symbol: 'YUM', name: 'Yum! Brands', sector: 'Consumer' },
  { symbol: 'CMG', name: 'Chipotle', sector: 'Consumer' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive', sector: 'Consumer' },
  { symbol: 'AZO', name: 'AutoZone', sector: 'Consumer' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer' },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer' },
  { symbol: 'DHI', name: 'DR Horton', sector: 'Consumer' },
  { symbol: 'LEN', name: 'Lennar', sector: 'Consumer' },
  { symbol: 'PHM', name: 'PulteGroup', sector: 'Consumer' },
  { symbol: 'DECK', name: 'Deckers Outdoor', sector: 'Consumer' },
  { symbol: 'EL', name: 'Estee Lauder', sector: 'Consumer' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer' },
  { symbol: 'KMB', name: 'Kimberly-Clark', sector: 'Consumer' },
  { symbol: 'GIS', name: 'General Mills', sector: 'Consumer' },
  { symbol: 'K', name: 'Kellanova', sector: 'Consumer' },
  { symbol: 'HSY', name: 'Hershey', sector: 'Consumer' },
  { symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer' },
  { symbol: 'STZ', name: 'Constellation Brands', sector: 'Consumer' },
  { symbol: 'TAP', name: 'Molson Coors', sector: 'Consumer' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Consumer' },
  { symbol: 'MO', name: 'Altria Group', sector: 'Consumer' },
  { symbol: 'SYY', name: 'Sysco', sector: 'Consumer' },
  { symbol: 'KHC', name: 'Kraft Heinz', sector: 'Consumer' },
  { symbol: 'MDLZ', name: 'Mondelez', sector: 'Consumer' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland', sector: 'Consumer' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance', sector: 'Consumer' },
  { symbol: 'DG', name: 'Dollar General', sector: 'Consumer' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer' },
  { symbol: 'BBY', name: 'Best Buy', sector: 'Consumer' },
  { symbol: 'ETSY', name: 'Etsy', sector: 'Consumer' },
  { symbol: 'W', name: 'Wayfair', sector: 'Consumer' },
  { symbol: 'CHWY', name: 'Chewy', sector: 'Consumer' },
  { symbol: 'CPNG', name: 'Coupang', sector: 'Consumer' },

  // ── Energy ──
  { symbol: 'XOM', name: 'ExxonMobil', sector: 'Energy' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources', sector: 'Energy' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'FANG', name: 'Diamondback Energy', sector: 'Energy' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'WMB', name: 'Williams Companies', sector: 'Energy' },
  { symbol: 'OKE', name: 'ONEOK', sector: 'Energy' },
  { symbol: 'ET', name: 'Energy Transfer', sector: 'Energy' },
  { symbol: 'TRGP', name: 'Targa Resources', sector: 'Energy' },
  { symbol: 'LNG', name: 'Cheniere Energy', sector: 'Energy' },

  // ── Industrial ──
  { symbol: 'BA', name: 'Boeing', sector: 'Industrial' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrial' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrial' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrial' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrial' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrial' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrial' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrial' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrial' },
  { symbol: 'CSX', name: 'CSX Corporation', sector: 'Industrial' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrial' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Industrial' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrial' },
  { symbol: 'HII', name: 'Huntington Ingalls', sector: 'Industrial' },
  { symbol: 'TDG', name: 'TransDigm Group', sector: 'Industrial' },
  { symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrial' },
  { symbol: 'EMR', name: 'Emerson Electric', sector: 'Industrial' },
  { symbol: 'ETN', name: 'Eaton Corporation', sector: 'Industrial' },
  { symbol: 'PH', name: 'Parker Hannifin', sector: 'Industrial' },
  { symbol: 'ROK', name: 'Rockwell Automation', sector: 'Industrial' },
  { symbol: 'CMI', name: 'Cummins', sector: 'Industrial' },
  { symbol: 'PCAR', name: 'PACCAR', sector: 'Industrial' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake', sector: 'Industrial' },
  { symbol: 'GWW', name: 'W.W. Grainger', sector: 'Industrial' },
  { symbol: 'FAST', name: 'Fastenal', sector: 'Industrial' },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrial' },
  { symbol: 'RSG', name: 'Republic Services', sector: 'Industrial' },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrial' },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Industrial' },
  { symbol: 'AAL', name: 'American Airlines', sector: 'Industrial' },
  { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrial' },
  { symbol: 'CARR', name: 'Carrier Global', sector: 'Industrial' },
  { symbol: 'VRSK', name: 'Verisk Analytics', sector: 'Industrial' },
  { symbol: 'IR', name: 'Ingersoll Rand', sector: 'Industrial' },
  { symbol: 'AME', name: 'AMETEK', sector: 'Industrial' },

  // ── Telecom / Media ──
  { symbol: 'T', name: 'AT&T', sector: 'Telecom' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Telecom' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Telecom' },
  { symbol: 'TMUS', name: 'T-Mobile', sector: 'Telecom' },
  { symbol: 'CHTR', name: 'Charter Communications', sector: 'Telecom' },
  { symbol: 'WBD', name: 'Warner Bros Discovery', sector: 'Telecom' },
  { symbol: 'PARA', name: 'Paramount Global', sector: 'Telecom' },
  { symbol: 'FOX', name: 'Fox Corporation', sector: 'Telecom' },
  { symbol: 'NWSA', name: 'News Corp', sector: 'Telecom' },
  { symbol: 'EA', name: 'Electronic Arts', sector: 'Telecom' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Telecom' },
  { symbol: 'ATVI', name: 'Activision Blizzard', sector: 'Telecom' },

  // ── Materials ──
  { symbol: 'LIN', name: 'Linde', sector: 'Materials' },
  { symbol: 'APD', name: 'Air Products', sector: 'Materials' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials' },
  { symbol: 'ECL', name: 'Ecolab', sector: 'Materials' },
  { symbol: 'DD', name: 'DuPont', sector: 'Materials' },
  { symbol: 'DOW', name: 'Dow Inc', sector: 'Materials' },
  { symbol: 'NEM', name: 'Newmont', sector: 'Materials' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials' },
  { symbol: 'NUE', name: 'Nucor', sector: 'Materials' },
  { symbol: 'STLD', name: 'Steel Dynamics', sector: 'Materials' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs', sector: 'Materials' },
  { symbol: 'VMC', name: 'Vulcan Materials', sector: 'Materials' },
  { symbol: 'MLM', name: 'Martin Marietta', sector: 'Materials' },
  { symbol: 'PPG', name: 'PPG Industries', sector: 'Materials' },
  { symbol: 'ALB', name: 'Albemarle', sector: 'Materials' },
  { symbol: 'CTVA', name: 'Corteva', sector: 'Materials' },
  { symbol: 'CF', name: 'CF Industries', sector: 'Materials' },
  { symbol: 'MOS', name: 'Mosaic Company', sector: 'Materials' },

  // ── Utilities ──
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { symbol: 'AEP', name: 'American Electric Power', sector: 'Utilities' },
  { symbol: 'SRE', name: 'Sempra Energy', sector: 'Utilities' },
  { symbol: 'EXC', name: 'Exelon', sector: 'Utilities' },
  { symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
  { symbol: 'PCG', name: 'PG&E', sector: 'Utilities' },
  { symbol: 'CEG', name: 'Constellation Energy', sector: 'Utilities' },
  { symbol: 'VST', name: 'Vistra', sector: 'Utilities' },
  { symbol: 'NRG', name: 'NRG Energy', sector: 'Utilities' },

  // ── Real Estate ──
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'SPG', name: 'Simon Property Group', sector: 'Real Estate' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'AVB', name: 'AvalonBay', sector: 'Real Estate' },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { symbol: 'ARE', name: 'Alexandria Real Estate', sector: 'Real Estate' },
  { symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },

  // ── Automotive ──
  { symbol: 'F', name: 'Ford Motor', sector: 'Automotive' },
  { symbol: 'GM', name: 'General Motors', sector: 'Automotive' },
  { symbol: 'RIVN', name: 'Rivian', sector: 'Automotive' },
  { symbol: 'LCID', name: 'Lucid Group', sector: 'Automotive' },
  { symbol: 'TM', name: 'Toyota Motor', sector: 'Automotive' },
  { symbol: 'STLA', name: 'Stellantis', sector: 'Automotive' },
  { symbol: 'NIO', name: 'NIO Inc', sector: 'Automotive' },
  { symbol: 'XPEV', name: 'XPeng', sector: 'Automotive' },
  { symbol: 'LI', name: 'Li Auto', sector: 'Automotive' },
  { symbol: 'APTV', name: 'Aptiv', sector: 'Automotive' },

  // ── Retail / Meme / High Vol ──
  { symbol: 'GME', name: 'GameStop', sector: 'Retail' },
  { symbol: 'AMC', name: 'AMC Entertainment', sector: 'Entertainment' },
  { symbol: 'MSTR', name: 'MicroStrategy', sector: 'Technology' },
  { symbol: 'CVNA', name: 'Carvana', sector: 'Consumer' },
  { symbol: 'CAVA', name: 'CAVA Group', sector: 'Consumer' },
  { symbol: 'CELH', name: 'Celsius Holdings', sector: 'Consumer' },
  { symbol: 'CROX', name: 'Crocs', sector: 'Consumer' },
  { symbol: 'BIRK', name: 'Birkenstock', sector: 'Consumer' },

  // ── Additional S&P 500 / Large Cap ──
  { symbol: 'ACN', name: 'Accenture', sector: 'Technology' },
  { symbol: 'IBM', name: 'IBM', sector: 'Technology' },
  { symbol: 'FSLR', name: 'First Solar', sector: 'Technology' },
  { symbol: 'ENPH', name: 'Enphase Energy', sector: 'Technology' },
  { symbol: 'SEDG', name: 'SolarEdge Technologies', sector: 'Technology' },
  { symbol: 'GPN', name: 'Global Payments', sector: 'Finance' },
  { symbol: 'TROW', name: 'T. Rowe Price', sector: 'Finance' },
  { symbol: 'CINF', name: 'Cincinnati Financial', sector: 'Finance' },
  { symbol: 'GL', name: 'Globe Life', sector: 'Finance' },
  { symbol: 'FLR', name: 'Fluor Corporation', sector: 'Industrial' },
  { symbol: 'J', name: 'Jacobs Solutions', sector: 'Industrial' },
  { symbol: 'PWR', name: 'Quanta Services', sector: 'Industrial' },
  { symbol: 'GNRC', name: 'Generac', sector: 'Industrial' },
  { symbol: 'TT', name: 'Trane Technologies', sector: 'Industrial' },
  { symbol: 'AXON', name: 'Axon Enterprise', sector: 'Industrial' },
  { symbol: 'CPRT', name: 'Copart', sector: 'Consumer' },
  { symbol: 'POOL', name: 'Pool Corporation', sector: 'Consumer' },
  { symbol: 'RCL', name: 'Royal Caribbean', sector: 'Consumer' },
  { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line', sector: 'Consumer' },
  { symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer' },
  { symbol: 'MGM', name: 'MGM Resorts', sector: 'Consumer' },
  { symbol: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer' },
  { symbol: 'EXPE', name: 'Expedia', sector: 'Consumer' },
  { symbol: 'TRIP', name: 'TripAdvisor', sector: 'Consumer' },
  { symbol: 'MTN', name: 'Vail Resorts', sector: 'Consumer' },
  { symbol: 'SBAC', name: 'SBA Communications', sector: 'Real Estate' },
  { symbol: 'EXR', name: 'Extra Space Storage', sector: 'Real Estate' },
  { symbol: 'MPW', name: 'Medical Properties Trust', sector: 'Real Estate' },
  { symbol: 'INVH', name: 'Invitation Homes', sector: 'Real Estate' },
  { symbol: 'BXP', name: 'BXP Inc', sector: 'Real Estate' },
  { symbol: 'WPC', name: 'W.P. Carey', sector: 'Real Estate' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy' },
  { symbol: 'MRO', name: 'Marathon Oil', sector: 'Energy' },
  { symbol: 'AR', name: 'Antero Resources', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy' },
  { symbol: 'CTRA', name: 'Coterra Energy', sector: 'Energy' },
  { symbol: 'AWK', name: 'American Water Works', sector: 'Utilities' },
  { symbol: 'WEC', name: 'WEC Energy', sector: 'Utilities' },
  { symbol: 'ES', name: 'Eversource Energy', sector: 'Utilities' },
  { symbol: 'BALL', name: 'Ball Corporation', sector: 'Materials' },
  { symbol: 'AVY', name: 'Avery Dennison', sector: 'Materials' },
  { symbol: 'PKG', name: 'Packaging Corp', sector: 'Materials' },
  { symbol: 'IP', name: 'International Paper', sector: 'Materials' },
  { symbol: 'ZBRA', name: 'Zebra Technologies', sector: 'Technology' },
  { symbol: 'MPWR', name: 'Monolithic Power', sector: 'Technology' },
  { symbol: 'ANSS', name: 'Ansys', sector: 'Technology' },
  { symbol: 'KEYS', name: 'Keysight Technologies', sector: 'Technology' },
  { symbol: 'TER', name: 'Teradyne', sector: 'Technology' },
  { symbol: 'TRMB', name: 'Trimble', sector: 'Technology' },
  { symbol: 'PTC', name: 'PTC Inc', sector: 'Technology' },
  { symbol: 'NTNX', name: 'Nutanix', sector: 'Technology' },
  { symbol: 'DUOL', name: 'Duolingo', sector: 'Technology' },
  { symbol: 'QLYS', name: 'Qualys', sector: 'Technology' },
  { symbol: 'SMAR', name: 'Smartsheet', sector: 'Technology' },
  { symbol: 'VEEV', name: 'Veeva Systems', sector: 'Healthcare' },
  { symbol: 'HOLX', name: 'Hologic', sector: 'Healthcare' },
  { symbol: 'WAT', name: 'Waters Corporation', sector: 'Healthcare' },
  { symbol: 'TECH', name: 'Bio-Techne', sector: 'Healthcare' },
  { symbol: 'XRAY', name: 'Dentsply Sirona', sector: 'Healthcare' },
  { symbol: 'RMD', name: 'ResMed', sector: 'Healthcare' },
  { symbol: 'MTD', name: 'Mettler-Toledo', sector: 'Healthcare' },
  { symbol: 'BIO', name: 'Bio-Rad Labs', sector: 'Healthcare' },
];

/** Get symbols only */
export function getUniverseSymbols(): string[] {
  return STOCK_UNIVERSE.map(s => s.symbol);
}

/** Lookup stock metadata */
export function getStockMeta(symbol: string): UniverseStock | undefined {
  return STOCK_UNIVERSE.find(s => s.symbol === symbol.toUpperCase());
}
