/**
 * Stock Universe for Screener
 *
 * ~500 most options-liquid US equities + major ETFs.
 * Curated by average daily options volume — excludes thin-options names
 * (small utilities, REITs, insurers, specialty industrials) and includes
 * popular non-S&P retail/growth/crypto names with heavy options flow.
 * Curated list of ~100 most actively traded US equities and ETFs,
 * sorted roughly by market cap / options liquidity.
 * These are the stocks with the deepest options markets — GEX/DEX
 * signals are most reliable where open interest and volume are highest.
 */

export interface UniverseStock {
  symbol: string;
  name: string;
  sector: string;
}

export const STOCK_UNIVERSE: UniverseStock[] = [
  // ── Major Index & Sector ETFs ──
  // ── Major ETFs ──
  { symbol: 'SPY', name: 'S&P 500 ETF', sector: 'ETF' },
  { symbol: 'QQQ', name: 'Nasdaq 100 ETF', sector: 'ETF' },
  { symbol: 'IWM', name: 'Russell 2000 ETF', sector: 'ETF' },
  { symbol: 'DIA', name: 'Dow Jones ETF', sector: 'ETF' },
  { symbol: 'XLF', name: 'Financial Select', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select', sector: 'ETF' },
  { symbol: 'XLV', name: 'Healthcare Select', sector: 'ETF' },
  { symbol: 'XLI', name: 'Industrial Select', sector: 'ETF' },
  { symbol: 'XLC', name: 'Communication Services', sector: 'ETF' },
  { symbol: 'XLU', name: 'Utilities Select', sector: 'ETF' },
  { symbol: 'XLP', name: 'Consumer Staples', sector: 'ETF' },
  { symbol: 'XLY', name: 'Consumer Discretionary', sector: 'ETF' },
  { symbol: 'XLB', name: 'Materials Select', sector: 'ETF' },
  { symbol: 'XLRE', name: 'Real Estate Select', sector: 'ETF' },

  // ── Thematic & Specialty ETFs ──
  { symbol: 'GLD', name: 'Gold ETF', sector: 'ETF' },
  { symbol: 'SLV', name: 'Silver ETF', sector: 'ETF' },
  { symbol: 'TLT', name: '20+ Year Treasury', sector: 'ETF' },
  { symbol: 'HYG', name: 'High Yield Bond', sector: 'ETF' },
  { symbol: 'EEM', name: 'Emerging Markets', sector: 'ETF' },
  { symbol: 'SMH', name: 'Semiconductor ETF', sector: 'ETF' },
  { symbol: 'SOXX', name: 'iShares Semiconductor', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation', sector: 'ETF' },
  { symbol: 'KWEB', name: 'China Internet', sector: 'ETF' },
  { symbol: 'XBI', name: 'SPDR Biotech', sector: 'ETF' },
  { symbol: 'KRE', name: 'Regional Banking', sector: 'ETF' },
  { symbol: 'FXI', name: 'China Large-Cap', sector: 'ETF' },
  { symbol: 'EWZ', name: 'Brazil ETF', sector: 'ETF' },
  { symbol: 'GDX', name: 'Gold Miners', sector: 'ETF' },
  { symbol: 'IBIT', name: 'iShares Bitcoin', sector: 'ETF' },
  { symbol: 'USO', name: 'US Oil Fund', sector: 'ETF' },
  { symbol: 'BITO', name: 'ProShares Bitcoin Strategy', sector: 'ETF' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', sector: 'ETF' },
  { symbol: 'SQQQ', name: 'ProShares UltraPro Short QQQ', sector: 'ETF' },
  { symbol: 'UVXY', name: 'ProShares Ultra VIX', sector: 'ETF' },

  // ═══════════════════════════════════════════════════════════
  // TOP EQUITIES BY OPTIONS VOLUME
  // ═══════════════════════════════════════════════════════════

  // ── Ultra-Liquid Mega-Caps ──
  { symbol: 'AAPL', name: 'Apple', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Technology' },
  { symbol: 'NVDA', name: 'NVIDIA', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Consumer Disc.' },
  { symbol: 'TSLA', name: 'Tesla', sector: 'Consumer Disc.' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Communication' },
  { symbol: 'GOOGL', name: 'Alphabet Class A', sector: 'Communication' },
  { symbol: 'GOOG', name: 'Alphabet Class C', sector: 'Communication' },
  { symbol: 'AMD', name: 'AMD', sector: 'Technology' },
  { symbol: 'INTC', name: 'Intel', sector: 'Technology' },
  { symbol: 'MU', name: 'Micron', sector: 'Technology' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Communication' },

  // ── High-Volume Non-S&P / Retail Favorites ──
  { symbol: 'SOFI', name: 'SoFi Technologies', sector: 'Finance' },
  { symbol: 'HOOD', name: 'Robinhood Markets', sector: 'Finance' },
  { symbol: 'NIO', name: 'NIO Inc', sector: 'Consumer Disc.' },
  { symbol: 'MARA', name: 'MARA Holdings', sector: 'Finance' },
  { symbol: 'RIOT', name: 'Riot Platforms', sector: 'Finance' },
  { symbol: 'AMC', name: 'AMC Entertainment', sector: 'Communication' },
  { symbol: 'GME', name: 'GameStop', sector: 'Consumer Disc.' },
  { symbol: 'RIVN', name: 'Rivian Automotive', sector: 'Consumer Disc.' },
  { symbol: 'LCID', name: 'Lucid Group', sector: 'Consumer Disc.' },
  { symbol: 'SNAP', name: 'Snap Inc', sector: 'Communication' },
  { symbol: 'RBLX', name: 'Roblox', sector: 'Communication' },
  { symbol: 'DKNG', name: 'DraftKings', sector: 'Consumer Disc.' },
  { symbol: 'BABA', name: 'Alibaba Group', sector: 'Consumer Disc.' },
  { symbol: 'JD', name: 'JD.com', sector: 'Consumer Disc.' },
  { symbol: 'PDD', name: 'PDD Holdings', sector: 'Consumer Disc.' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Technology' },
  { symbol: 'SQ', name: 'Block Inc', sector: 'Finance' },
  { symbol: 'MSTR', name: 'MicroStrategy', sector: 'Technology' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Technology' },
  { symbol: 'ROKU', name: 'Roku', sector: 'Communication' },
  { symbol: 'ARM', name: 'Arm Holdings', sector: 'Technology' },
  { symbol: 'AFRM', name: 'Affirm Holdings', sector: 'Finance' },
  { symbol: 'UPST', name: 'Upstart Holdings', sector: 'Finance' },
  { symbol: 'CVNA', name: 'Carvana', sector: 'Consumer Disc.' },
  { symbol: 'LYFT', name: 'Lyft', sector: 'Industrial' },
  { symbol: 'PINS', name: 'Pinterest', sector: 'Communication' },
  { symbol: 'AI', name: 'C3.ai', sector: 'Technology' },
  { symbol: 'IONQ', name: 'IonQ', sector: 'Technology' },
  { symbol: 'SOUN', name: 'SoundHound AI', sector: 'Technology' },
  { symbol: 'PLUG', name: 'Plug Power', sector: 'Industrial' },
  { symbol: 'FUBO', name: 'fuboTV', sector: 'Communication' },
  { symbol: 'SE', name: 'Sea Limited', sector: 'Communication' },
  { symbol: 'GRAB', name: 'Grab Holdings', sector: 'Technology' },
  { symbol: 'XPEV', name: 'XPeng', sector: 'Consumer Disc.' },
  { symbol: 'LI', name: 'Li Auto', sector: 'Consumer Disc.' },
  { symbol: 'BIDU', name: 'Baidu', sector: 'Communication' },
  { symbol: 'PATH', name: 'UiPath', sector: 'Technology' },
  { symbol: 'U', name: 'Unity Software', sector: 'Technology' },
  { symbol: 'CHWY', name: 'Chewy', sector: 'Consumer Disc.' },
  { symbol: 'OPEN', name: 'Opendoor Technologies', sector: 'Real Estate' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs', sector: 'Materials' },
  { symbol: 'VALE', name: 'Vale SA', sector: 'Materials' },
  { symbol: 'X', name: 'United States Steel', sector: 'Materials' },
  { symbol: 'RIG', name: 'Transocean', sector: 'Energy' },
  { symbol: 'ET', name: 'Energy Transfer', sector: 'Energy' },
  { symbol: 'OKLO', name: 'Oklo Inc', sector: 'Energy' },
  { symbol: 'ASTS', name: 'AST SpaceMobile', sector: 'Communication' },
  { symbol: 'RKLB', name: 'Rocket Lab USA', sector: 'Industrial' },
  { symbol: 'ACHR', name: 'Archer Aviation', sector: 'Industrial' },
  { symbol: 'JOBY', name: 'Joby Aviation', sector: 'Industrial' },
  { symbol: 'DNA', name: 'Ginkgo Bioworks', sector: 'Healthcare' },
  { symbol: 'BILL', name: 'BILL Holdings', sector: 'Technology' },
  { symbol: 'WOLF', name: 'Wolfspeed', sector: 'Technology' },

  // ── Large-Cap Technology ──
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Technology' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Technology' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Technology' },
  { symbol: 'ACN', name: 'Accenture', sector: 'Technology' },
  { symbol: 'IBM', name: 'IBM', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology' },
  { symbol: 'PLTR', name: 'Palantir', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys', sector: 'Technology' },
  { symbol: 'CDNS', name: 'Cadence Design', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },
  { symbol: 'ANET', name: 'Arista Networks', sector: 'Technology' },
  { symbol: 'SMCI', name: 'Super Micro Computer', sector: 'Technology' },
  { symbol: 'APH', name: 'Amphenol', sector: 'Technology' },
  { symbol: 'ADSK', name: 'Autodesk', sector: 'Technology' },
  { symbol: 'FTNT', name: 'Fortinet', sector: 'Technology' },
  { symbol: 'DELL', name: 'Dell Technologies', sector: 'Technology' },
  { symbol: 'MSI', name: 'Motorola Solutions', sector: 'Technology' },
  { symbol: 'DDOG', name: 'Datadog', sector: 'Technology' },
  { symbol: 'WDAY', name: 'Workday', sector: 'Technology' },
  { symbol: 'ROP', name: 'Roper Technologies', sector: 'Technology' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },
  { symbol: 'ON', name: 'ON Semiconductor', sector: 'Technology' },
  { symbol: 'MPWR', name: 'Monolithic Power', sector: 'Technology' },
  { symbol: 'FICO', name: 'Fair Isaac', sector: 'Technology' },
  { symbol: 'MCHP', name: 'Microchip Technology', sector: 'Technology' },
  { symbol: 'FSLR', name: 'First Solar', sector: 'Technology' },
  { symbol: 'CDW', name: 'CDW Corporation', sector: 'Technology' },
  { symbol: 'CTSH', name: 'Cognizant', sector: 'Technology' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Technology' },
  { symbol: 'HPQ', name: 'HP Inc', sector: 'Technology' },
  { symbol: 'GLW', name: 'Corning', sector: 'Technology' },
  { symbol: 'KEYS', name: 'Keysight Technologies', sector: 'Technology' },
  { symbol: 'GDDY', name: 'GoDaddy', sector: 'Technology' },
  { symbol: 'TEL', name: 'TE Connectivity', sector: 'Technology' },
  { symbol: 'GEN', name: 'Gen Digital', sector: 'Technology' },
  { symbol: 'NTAP', name: 'NetApp', sector: 'Technology' },
  { symbol: 'SWKS', name: 'Skyworks Solutions', sector: 'Technology' },
  { symbol: 'STX', name: 'Seagate Technology', sector: 'Technology' },
  { symbol: 'WDC', name: 'Western Digital', sector: 'Technology' },
  { symbol: 'ENPH', name: 'Enphase Energy', sector: 'Technology' },

  // ── Communication Services ──
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Communication' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Communication' },
  { symbol: 'TMUS', name: 'T-Mobile', sector: 'Communication' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication' },
  { symbol: 'CHTR', name: 'Charter Communications', sector: 'Communication' },
  { symbol: 'TTD', name: 'The Trade Desk', sector: 'Communication' },
  { symbol: 'EA', name: 'Electronic Arts', sector: 'Communication' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication' },
  { symbol: 'WBD', name: 'Warner Bros Discovery', sector: 'Communication' },
  { symbol: 'LYV', name: 'Live Nation', sector: 'Communication' },
  { symbol: 'MTCH', name: 'Match Group', sector: 'Communication' },

  // ── Consumer Discretionary ──
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer Disc.' },
  { symbol: 'MCD', name: 'McDonald\'s', sector: 'Consumer Disc.' },
  { symbol: 'LOW', name: 'Lowe\'s', sector: 'Consumer Disc.' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Disc.' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer Disc.' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Disc.' },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer Disc.' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Consumer Disc.' },
  { symbol: 'CMG', name: 'Chipotle', sector: 'Consumer Disc.' },
  { symbol: 'MAR', name: 'Marriott', sector: 'Consumer Disc.' },
  { symbol: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer Disc.' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive', sector: 'Consumer Disc.' },
  { symbol: 'AZO', name: 'AutoZone', sector: 'Consumer Disc.' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer Disc.' },
  { symbol: 'DHI', name: 'DR Horton', sector: 'Consumer Disc.' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Consumer Disc.' },
  { symbol: 'GM', name: 'General Motors', sector: 'Consumer Disc.' },
  { symbol: 'F', name: 'Ford Motor', sector: 'Consumer Disc.' },
  { symbol: 'LEN', name: 'Lennar', sector: 'Consumer Disc.' },
  { symbol: 'YUM', name: 'Yum! Brands', sector: 'Consumer Disc.' },
  { symbol: 'LULU', name: 'Lululemon', sector: 'Consumer Disc.' },
  { symbol: 'PHM', name: 'PulteGroup', sector: 'Consumer Disc.' },
  { symbol: 'DECK', name: 'Deckers Outdoor', sector: 'Consumer Disc.' },
  { symbol: 'RCL', name: 'Royal Caribbean', sector: 'Consumer Disc.' },
  { symbol: 'EXPE', name: 'Expedia', sector: 'Consumer Disc.' },
  { symbol: 'BBY', name: 'Best Buy', sector: 'Consumer Disc.' },
  { symbol: 'APTV', name: 'Aptiv', sector: 'Consumer Disc.' },
  { symbol: 'GRMN', name: 'Garmin', sector: 'Consumer Disc.' },
  { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer Disc.' },
  { symbol: 'DRI', name: 'Darden Restaurants', sector: 'Consumer Disc.' },
  { symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Consumer Disc.' },
  { symbol: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer Disc.' },
  { symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer Disc.' },
  { symbol: 'CZR', name: 'Caesars Entertainment', sector: 'Consumer Disc.' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line', sector: 'Consumer Disc.' },
  { symbol: 'MGM', name: 'MGM Resorts', sector: 'Consumer Disc.' },
  { symbol: 'DPZ', name: 'Domino\'s Pizza', sector: 'Consumer Disc.' },
  { symbol: 'KMX', name: 'CarMax', sector: 'Consumer Disc.' },
  { symbol: 'EBAY', name: 'eBay', sector: 'Consumer Disc.' },
  { symbol: 'WSM', name: 'Williams-Sonoma', sector: 'Consumer Disc.' },
  { symbol: 'TPR', name: 'Tapestry', sector: 'Consumer Disc.' },
  { symbol: 'BLDR', name: 'Builders FirstSource', sector: 'Consumer Disc.' },
  { symbol: 'NVR', name: 'NVR Inc', sector: 'Consumer Disc.' },

  // ── Consumer Staples ──
  { symbol: 'WMT', name: 'Walmart', sector: 'Staples' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Staples' },
  { symbol: 'COST', name: 'Costco', sector: 'Staples' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Staples' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Staples' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Staples' },
  { symbol: 'MO', name: 'Altria Group', sector: 'Staples' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Staples' },
  { symbol: 'MDLZ', name: 'Mondelez', sector: 'Staples' },
  { symbol: 'TGT', name: 'Target', sector: 'Staples' },
  { symbol: 'SYY', name: 'Sysco', sector: 'Staples' },
  { symbol: 'STZ', name: 'Constellation Brands', sector: 'Staples' },
  { symbol: 'KHC', name: 'Kraft Heinz', sector: 'Staples' },
  { symbol: 'MNST', name: 'Monster Beverage', sector: 'Staples' },
  { symbol: 'KR', name: 'Kroger', sector: 'Staples' },
  { symbol: 'EL', name: 'Estee Lauder', sector: 'Staples' },
  { symbol: 'KVUE', name: 'Kenvue', sector: 'Staples' },
  { symbol: 'DG', name: 'Dollar General', sector: 'Staples' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Staples' },
  { symbol: 'WBA', name: 'Walgreens', sector: 'Staples' },

  // ── Financials ──
  { symbol: 'BRK.B', name: 'Berkshire Hathaway', sector: 'Finance' },
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Finance' },
  { symbol: 'V', name: 'Visa', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Finance' },
  { symbol: 'XLF', name: 'Financial Select Sector', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select Sector', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select Sector', sector: 'ETF' },
  { symbol: 'GLD', name: 'Gold ETF', sector: 'ETF' },
  { symbol: 'TLT', name: '20+ Year Treasury ETF', sector: 'ETF' },
  { symbol: 'HYG', name: 'High Yield Corporate Bond ETF', sector: 'ETF' },
  { symbol: 'EEM', name: 'Emerging Markets ETF', sector: 'ETF' },
  { symbol: 'SLV', name: 'Silver ETF', sector: 'ETF' },

  // ── Mega Cap Tech ──
  { symbol: 'AAPL', name: 'Apple', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Technology' },
  { symbol: 'NVDA', name: 'NVIDIA', sector: 'Technology' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Technology' },
  { symbol: 'TSLA', name: 'Tesla', sector: 'Technology' },
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Technology' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Technology' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology' },
  { symbol: 'AMD', name: 'AMD', sector: 'Technology' },
  { symbol: 'INTC', name: 'Intel', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe', sector: 'Technology' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'MU', name: 'Micron', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Technology' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Technology' },
  { symbol: 'SNOW', name: 'Snowflake', sector: 'Technology' },
  { symbol: 'PLTR', name: 'Palantir', sector: 'Technology' },
  { symbol: 'ARM', name: 'ARM Holdings', sector: 'Technology' },
  { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },

  // ── Finance ──
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Finance' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Finance' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Finance' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Finance' },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Finance' },
  { symbol: 'C', name: 'Citigroup', sector: 'Finance' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Finance' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Finance' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Finance' },
  { symbol: 'CME', name: 'CME Group', sector: 'Finance' },
  { symbol: 'PGR', name: 'Progressive', sector: 'Finance' },
  { symbol: 'MCO', name: "Moody's", sector: 'Finance' },
  { symbol: 'KKR', name: 'KKR & Co', sector: 'Finance' },
  { symbol: 'APO', name: 'Apollo Global', sector: 'Finance' },
  { symbol: 'BX', name: 'Blackstone', sector: 'Finance' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Finance' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Finance' },
  { symbol: 'COF', name: 'Capital One Financial', sector: 'Finance' },
  { symbol: 'AIG', name: 'American Intl Group', sector: 'Finance' },
  { symbol: 'MET', name: 'MetLife', sector: 'Finance' },
  { symbol: 'AFL', name: 'Aflac', sector: 'Finance' },
  { symbol: 'PRU', name: 'Prudential Financial', sector: 'Finance' },
  { symbol: 'TRV', name: 'Travelers Companies', sector: 'Finance' },
  { symbol: 'ALL', name: 'Allstate', sector: 'Finance' },
  { symbol: 'USB', name: 'US Bancorp', sector: 'Finance' },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Finance' },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Finance' },
  { symbol: 'DFS', name: 'Discover Financial', sector: 'Finance' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Finance' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Finance' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Finance' },
  { symbol: 'RF', name: 'Regions Financial', sector: 'Finance' },
  { symbol: 'CFG', name: 'Citizens Financial', sector: 'Finance' },
  { symbol: 'SYF', name: 'Synchrony Financial', sector: 'Finance' },
  { symbol: 'FI', name: 'Fiserv', sector: 'Finance' },
  { symbol: 'FIS', name: 'Fidelity National Info', sector: 'Finance' },
  { symbol: 'AMP', name: 'Ameriprise Financial', sector: 'Finance' },
  { symbol: 'TROW', name: 'T. Rowe Price', sector: 'Finance' },
  { symbol: 'RJF', name: 'Raymond James', sector: 'Finance' },
  { symbol: 'STT', name: 'State Street', sector: 'Finance' },
  { symbol: 'BK', name: 'Bank of New York Mellon', sector: 'Finance' },

  // ── Health Care ──
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck', sector: 'Healthcare' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { symbol: 'ABT', name: 'Abbott Labs', sector: 'Healthcare' },
  { symbol: 'DHR', name: 'Danaher', sector: 'Healthcare' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'SYK', name: 'Stryker', sector: 'Healthcare' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Healthcare' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
  { symbol: 'CI', name: 'Cigna Group', sector: 'Healthcare' },
  { symbol: 'REGN', name: 'Regeneron', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'MCK', name: 'McKesson', sector: 'Healthcare' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Healthcare' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Healthcare' },
  { symbol: 'IQV', name: 'IQVIA Holdings', sector: 'Healthcare' },
  { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare' },
  { symbol: 'A', name: 'Agilent Technologies', sector: 'Healthcare' },
  { symbol: 'IDXX', name: 'IDEXX Labs', sector: 'Healthcare' },
  { symbol: 'COR', name: 'Cencora', sector: 'Healthcare' },
  { symbol: 'BDX', name: 'Becton Dickinson', sector: 'Healthcare' },
  { symbol: 'BIIB', name: 'Biogen', sector: 'Healthcare' },
  { symbol: 'HUM', name: 'Humana', sector: 'Healthcare' },
  { symbol: 'CNC', name: 'Centene', sector: 'Healthcare' },
  { symbol: 'CAH', name: 'Cardinal Health', sector: 'Healthcare' },
  { symbol: 'DXCM', name: 'DexCom', sector: 'Healthcare' },
  { symbol: 'ALGN', name: 'Align Technology', sector: 'Healthcare' },
  { symbol: 'PODD', name: 'Insulet', sector: 'Healthcare' },
  { symbol: 'LH', name: 'Labcorp', sector: 'Healthcare' },
  { symbol: 'HOLX', name: 'Hologic', sector: 'Healthcare' },
  { symbol: 'INCY', name: 'Incyte', sector: 'Healthcare' },
  { symbol: 'RMD', name: 'ResMed', sector: 'Healthcare' },
  { symbol: 'V', name: 'Visa', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Finance' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway', sector: 'Finance' },
  { symbol: 'C', name: 'Citigroup', sector: 'Finance' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance' },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Finance' },
  { symbol: 'SQ', name: 'Block (Square)', sector: 'Finance' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Finance' },

  // ── Healthcare ──
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Healthcare' },

  // ── Consumer ──
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer' },
  { symbol: 'COST', name: 'Costco', sector: 'Consumer' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer' },
  { symbol: 'MCD', name: "McDonald's", sector: 'Consumer' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer' },
  { symbol: 'LOW', name: "Lowe's", sector: 'Consumer' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Consumer' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer' },
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Consumer' },

  // ── Energy ──
  { symbol: 'XOM', name: 'ExxonMobil', sector: 'Energy' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'WMB', name: 'Williams Companies', sector: 'Energy' },
  { symbol: 'OKE', name: 'ONEOK', sector: 'Energy' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'FANG', name: 'Diamondback Energy', sector: 'Energy' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'TRGP', name: 'Targa Resources', sector: 'Energy' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'CTRA', name: 'Coterra Energy', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy' },

  // ── Industrials ──
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrial' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrial' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Industrial' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrial' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrial' },
  { symbol: 'ETN', name: 'Eaton Corporation', sector: 'Industrial' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrial' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrial' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial' },
  { symbol: 'ADP', name: 'Automatic Data Processing', sector: 'Industrial' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrial' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrial' },
  { symbol: 'TT', name: 'Trane Technologies', sector: 'Industrial' },
  { symbol: 'GEV', name: 'GE Vernova', sector: 'Industrial' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Industrial' },
  { symbol: 'PH', name: 'Parker Hannifin', sector: 'Industrial' },
  { symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrial' },
  { symbol: 'AXON', name: 'Axon Enterprise', sector: 'Industrial' },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrial' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrial' },
  { symbol: 'TDG', name: 'TransDigm Group', sector: 'Industrial' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrial' },
  { symbol: 'CSX', name: 'CSX Corporation', sector: 'Industrial' },
  { symbol: 'EMR', name: 'Emerson Electric', sector: 'Industrial' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrial' },
  { symbol: 'CTAS', name: 'Cintas', sector: 'Industrial' },
  { symbol: 'CARR', name: 'Carrier Global', sector: 'Industrial' },
  { symbol: 'URI', name: 'United Rentals', sector: 'Industrial' },
  { symbol: 'CPRT', name: 'Copart', sector: 'Industrial' },
  { symbol: 'GWW', name: 'W.W. Grainger', sector: 'Industrial' },
  { symbol: 'FAST', name: 'Fastenal', sector: 'Industrial' },
  { symbol: 'CMI', name: 'Cummins', sector: 'Industrial' },
  { symbol: 'PCAR', name: 'PACCAR', sector: 'Industrial' },
  { symbol: 'VRSK', name: 'Verisk Analytics', sector: 'Industrial' },
  { symbol: 'ODFL', name: 'Old Dominion Freight', sector: 'Industrial' },
  { symbol: 'PWR', name: 'Quanta Services', sector: 'Industrial' },
  { symbol: 'IR', name: 'Ingersoll Rand', sector: 'Industrial' },
  { symbol: 'RSG', name: 'Republic Services', sector: 'Industrial' },
  { symbol: 'HWM', name: 'Howmet Aerospace', sector: 'Industrial' },
  { symbol: 'AME', name: 'AMETEK', sector: 'Industrial' },
  { symbol: 'OTIS', name: 'Otis Worldwide', sector: 'Industrial' },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrial' },
  { symbol: 'LHX', name: 'L3Harris Technologies', sector: 'Industrial' },
  { symbol: 'ROK', name: 'Rockwell Automation', sector: 'Industrial' },
  { symbol: 'PAYX', name: 'Paychex', sector: 'Industrial' },
  { symbol: 'GNRC', name: 'Generac', sector: 'Industrial' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake', sector: 'Industrial' },
  { symbol: 'LDOS', name: 'Leidos Holdings', sector: 'Industrial' },
  { symbol: 'EFX', name: 'Equifax', sector: 'Industrial' },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Industrial' },
  { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrial' },
  { symbol: 'AAL', name: 'American Airlines', sector: 'Industrial' },
  { symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrial' },
  { symbol: 'MMM', name: '3M', sector: 'Industrial' },
  { symbol: 'PAYC', name: 'Paycom', sector: 'Industrial' },

  // ── Materials ──
  { symbol: 'LIN', name: 'Linde', sector: 'Materials' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials' },
  { symbol: 'APD', name: 'Air Products', sector: 'Materials' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials' },
  { symbol: 'ECL', name: 'Ecolab', sector: 'Materials' },
  { symbol: 'NEM', name: 'Newmont', sector: 'Materials' },
  { symbol: 'DOW', name: 'Dow Inc', sector: 'Materials' },
  { symbol: 'DD', name: 'DuPont', sector: 'Materials' },
  { symbol: 'NUE', name: 'Nucor', sector: 'Materials' },
  { symbol: 'VMC', name: 'Vulcan Materials', sector: 'Materials' },
  { symbol: 'PPG', name: 'PPG Industries', sector: 'Materials' },
  { symbol: 'CTVA', name: 'Corteva', sector: 'Materials' },
  { symbol: 'STLD', name: 'Steel Dynamics', sector: 'Materials' },
  { symbol: 'ALB', name: 'Albemarle', sector: 'Materials' },
  { symbol: 'CF', name: 'CF Industries', sector: 'Materials' },
  { symbol: 'LYB', name: 'LyondellBasell', sector: 'Materials' },
  { symbol: 'BALL', name: 'Ball Corporation', sector: 'Materials' },
  { symbol: 'MOS', name: 'Mosaic Company', sector: 'Materials' },

  // ── Real Estate (liquid names only) ──
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { symbol: 'SPG', name: 'Simon Property Group', sector: 'Real Estate' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'CBRE', name: 'CBRE Group', sector: 'Real Estate' },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },

  // ── Utilities (liquid names only) ──
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'CEG', name: 'Constellation Energy', sector: 'Utilities' },
  { symbol: 'VST', name: 'Vistra', sector: 'Utilities' },
  { symbol: 'SRE', name: 'Sempra Energy', sector: 'Utilities' },
  { symbol: 'AEP', name: 'American Electric Power', sector: 'Utilities' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { symbol: 'PCG', name: 'PG&E', sector: 'Utilities' },
  { symbol: 'EXC', name: 'Exelon', sector: 'Utilities' },
  { symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
  { symbol: 'NRG', name: 'NRG Energy', sector: 'Utilities' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },

  // ── Industrial / Other ──
  { symbol: 'BA', name: 'Boeing', sector: 'Industrial' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrial' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrial' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrial' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrial' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrial' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrial' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrial' },

  // ── Telecom / Media ──
  { symbol: 'T', name: 'AT&T', sector: 'Telecom' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Telecom' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Telecom' },
  { symbol: 'TMUS', name: 'T-Mobile', sector: 'Telecom' },

  // ── Meme / High Vol ──
  { symbol: 'GME', name: 'GameStop', sector: 'Retail' },
  { symbol: 'AMC', name: 'AMC Entertainment', sector: 'Entertainment' },
  { symbol: 'RIVN', name: 'Rivian', sector: 'Automotive' },
  { symbol: 'LCID', name: 'Lucid Group', sector: 'Automotive' },
  { symbol: 'SOFI', name: 'SoFi Technologies', sector: 'Finance' },
  { symbol: 'SMCI', name: 'Super Micro Computer', sector: 'Technology' },
];

/** Get symbols only */
export function getUniverseSymbols(): string[] {
  return STOCK_UNIVERSE.map(s => s.symbol);
}

/** Lookup stock metadata */
export function getStockMeta(symbol: string): UniverseStock | undefined {
  return STOCK_UNIVERSE.find(s => s.symbol === symbol.toUpperCase());
}
